CREATE TABLE deposit (
    id INTEGER PRIMARY KEY,
    store_id INTEGER NOT NULL REFERENCES stores(id),
    user_id INTEGER NOT NULL REFERENCES users(id),
    ils_200 REAL,
    ils_100 REAL,
    ils_50 REAL,
    ils_20 REAL,
    ils_10 REAL,
    ils_5 REAL,
    ils_2 REAL,
    ils_1 REAL,
    ils_05 REAL,
    usd_100 REAL,
    usd_50 REAL,
    usd_20 REAL,
    usd_10 REAL,
    usd_5 REAL,
    usd_2 REAL,
    usd_1 REAL,
    jod_50 REAL,
    jod_20 REAL,
    jod_10 REAL,
    jod_5 REAL,
    jod_1 REAL,
    rate_usd REAL,
    rate_jod REAL,
    cdate DATE NOT NULL,
    timestamp TEXT DEFAULT CURRENT_TIMESTAMP, cdate_new DATE,
    FOREIGN KEY (store_id) REFERENCES stores(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);